add PSA SoC
openWB/openwb-ui-settings pull request #200
Opened 2022-11-13 22:08 UTC by MartinRinas

Fügt die Konfigurationsseite für die PSA Modelle hinzu.

2022-11-13 22:09 UTC, MartinRinas commented
gehört zu https://github.com/openWB/core/pull/637

2022-11-14 06:35 UTC, benderl requested changes

2022-11-14 06:35 UTC, benderl commented on src/components/vehicles/psa/vehicle.vue
> +	<div class="vehicle-soc-vwid">
```suggestion
	<div class="vehicle-soc-psa">
```

2022-11-14 06:55 UTC, MartinRinas commented on src/components/vehicles/psa/vehicle.vue
> +	<div class="vehicle-soc-vwid">
ah ja danke, das hab' ich übersehen. Ist korrigiert.

2022-11-14 08:07 UTC, benderl commented on src/components/vehicles/psa/vehicle.vue
> +	<div class="vehicle-soc-vwid">
Passiert mir auch regelmäßig. Eigentlich wird die Klasse nicht mehr benötigt. Wenn die aktuellen PRs zu den SoC Modulen drin sind, überarbeite ich das komplett.

2022-11-14 08:08 UTC, benderl approved these changes

2022-11-24 10:21 UTC, merged