pointstyle false
openWB/openwb-ui-settings pull request #277
Opened 2023-05-26 20:58 UTC by MartinRinas

PointStyle false für bessere Lesbarkeit der Tagesauswertung

2023-05-30 09:34 UTC, benderl commented on src/views/DailyChart.vue
> +					pointStyle: false,
```suggestion
					pointStyle: "circle",
					pointRadius: 0,
					pointHoverRadius: 4,
```

2023-05-30 09:34 UTC, benderl commented on src/views/DailyChart.vue
> +					pointStyle: false,
```suggestion
					pointStyle: "circle",
					pointRadius: 0,
					pointHoverRadius: 4,
```

2023-05-30 09:35 UTC, benderl commented on src/views/DailyChart.vue
> +					pointStyle: false,
```suggestion
					pointStyle: "circle",
					pointRadius: 0,
					pointHoverRadius: 4,
```

2023-05-30 09:35 UTC, benderl commented on src/views/DailyChart.vue
> +					pointStyle: false,
```suggestion
					pointStyle: "circle",
					pointRadius: 0,
					pointHoverRadius: 4,
```

2023-05-30 09:50 UTC, MartinRinas commented
Ja, das gefällt mir gut so. Gerade auf dem Handy ist das mit den Datenbunkten in den Diagrammen sonst recht unübersichtlich.

2023-05-31 05:20 UTC, benderl requested changes
Bei der Überarbeitung ist die `DailyChart.vue` irgendwie durcheinander gekommen. Da fehlen ein paar abschließende `}`.

2023-05-31 07:19 UTC, benderl commented
Da ich gerade eh die Einstellungen neu baue, habe ich das schnell mal selbst übernommen.
#279

2023-05-31 07:19 UTC, closed without merging