GUI Anfassungen für "Update samba Modul #1187"
openWB/openwb-ui-settings pull request #367
Opened 2023-10-21 16:51 UTC by Saharel001

Siehe PR in core

2023-10-22 06:11 UTC, Saharel001 commented
![image](https://github.com/openWB/openwb-ui-settings/assets/24453343/50bf0b03-3082-468d-946f-34c0329a7cb0)

Das ist das Ergebnis. Ich bin damit jetzt fertig.

2023-10-23 06:46 UTC, benderl requested changes

2023-10-23 06:46 UTC, benderl commented on src/components/backup_clouds/samba/backup_cloud.vue
> +			pattern="(.*/)*"
Alle ungültigen Zeichen sollten zu einem Eingabefehler fürhren. Das Pattern bitte entsprechend anpassen.
`" \ / : | < > * ?`

2023-10-23 12:49 UTC, Saharel001 commented on src/components/backup_clouds/samba/backup_cloud.vue
> +			pattern="(.*/)*"
Bin dran, allerdings muss / drin bleiben. Ist das Trennzeichen für die Pfade.

2023-10-24 08:50 UTC, Saharel001 commented on src/components/backup_clouds/samba/backup_cloud.vue
> +			pattern="(.*/)*"
@bender Ist nun drin

2023-10-24 08:54 UTC, Saharel001 reviewed
erledigt

2023-10-25 08:39 UTC, benderl approved these changes

2023-11-06 10:20 UTC, benderl commented on src/components/backup_clouds/samba/backup_cloud.vue
> +				Die Zeichen \:"|*?&lt&gt sind verboten!<br />
Bei den HTML Entities fehlt noch das abschließende Semikolon.
```suggestion
				Die Zeichen \:"|*?&lt;&gt; sind verboten!<br />
```

2023-11-07 07:44 UTC, merged