Boersenmodul
openWB/openwb-ui-settings pull request #451
Opened 2024-04-18 08:27 UTC by pama87

Erste Version Boersenmodul: Vom Menu -> Ladeeinstellungen -> Übergreifendes unter Optional kann als Anbieter Energy Charts ausgewählt werden, wodurch die Börsenstrompreise von energy-charts.info abgerufen werden. Weiterhin kann das Land ausgewählt werden und ein Aufschlag auf den Börsenpreis in Cent / kWh angegeben werden.

2024-04-18 12:34 UTC, LKuemmel requested changes

2024-04-18 12:34 UTC, LKuemmel commented on src/views/GeneralChargeConfig.vue
Die Änderungen in dieser Datei bitte noch entfernen. der Preisaufschlag wird nur innerhalb des Börsenmoduls verwendet.

2024-04-18 12:34 UTC, LKuemmel commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +				{ value: 'at', text: 'Österreich' },
```suggestion
				{ value: 'DE-LU', text: 'Deutschland' },
				{ value: 'AT', text: 'Österreich' },
```
So kannst Du dir das matching im Backend sparen.

Wir brauchen als Länder nur Deutschland, Österreich und Schweiz. In anderen Ländern wird die openWB nicht vertreiben.

2024-04-18 12:38 UTC, pama87 commented on src/views/GeneralChargeConfig.vue
Wird dann dadurch nicht der Wert im Input Feld entfernt? Ich glaube ich habe das Topic abonniert, damit der Input nicht leer ist. Ansonsten zeigt es da keinen Wert an, oder?

2024-04-19 07:39 UTC, LKuemmel approved these changes

2024-04-25 09:22 UTC, benderl requested changes

2024-04-25 09:22 UTC, benderl commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +		</openwb-base-select-input>
Der Hilfetext gehört nicht zu der Einstellung "Land", sondern ist eine allgemeine Info zu dem Modul. Bitte in einen eigenen Info-Block direkt nach `<div class="electricity-tariff-energycharts">` verschieben.
```suggestion
		<openwb-base-alert subtype="info">
			Börsenstrompreise von Energy Charts (energy-charts.info)<br />
			Die Rohdaten werden von Wissenschaftlern des Fraunhofer-Institut
			für Solare Energiesysteme ISE aus zahlreichen Quellen stündlich
			oder täglich abgerufen und für die Darstellung aufbereitet.
		</openwb-base-alert>
		<openwb-base-select-input
			title="Land"
			notSelected="Bitte auswählen"
			:options="[
				{ value: 'DE-LU', text: 'Deutschland' },
				{ value: 'AT', text: 'Österreich' },
				{ value: 'CH', text: 'Schweiz' },
			]"
			:model-value="electricityTariff.configuration.country"
			@update:model-value="
				updateConfiguration($event, 'configuration.country')
			"
		/>
```

2024-04-25 09:22 UTC, benderl commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +					</openwb-base-number-input>
Hier stimmt die Einrückung nicht mehr.

2024-04-25 09:30 UTC, benderl commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +						:model-value="electricityTariff.configuration.serve_price"
Ich habe ziemlich lange gebraucht, um zu verstehen, was mit `serve_price` gemeint ist. Wenn Du "Preisaufschlag" meinst, dann ist der Begriff `serve` für den Aufschlag im Tennis nicht passend. Besser `surcharge` verwenden.

2024-04-25 10:02 UTC, benderl requested changes

2024-04-25 10:02 UTC, benderl commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +		</openwb-base-number-input>
```suggestion
		<openwb-base-number-input
			title="Aufschlag zum Börsenstrompreis"
			:min=0
			:step="0.001"
			:precision="3"
			unit="ct/kWh"
			:model-value="electricityTariff.configuration.surcharge"
			@update:model-value="
				updateConfiguration(parseFloat(($event).toFixed(7)), 'configuration.surcharge')
			"
		>
			<template #help>
				Die Auswahl (Energy-Charts) kann für alle Stromanbieter ausgewählt werden,
				die die Börsenstrompreise in einem variablen/dynamischen Tarif an die Kunden
				weitergeben. Das Modul soll es ermöglichen, dass zu tagesaktuellen Strompreisen
				unter Berücksichtigung eines Aufschlags zu günstigen Zeiten automatisch geladen
				werden kann und somit die Preisschwankungen an der Börse optimal ausgenutzt werden.
			</template>
		</openwb-base-number-input>
```

2024-04-25 10:08 UTC, benderl commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +							updateConfiguration(parseFloat(($event).toFixed(7)), 'configuration.surchar_price')
Wenn das Eingabefeld auf drei Nachkommastellen begrenzt ist, warum verwendest Du dann hier 7?

2024-04-25 10:28 UTC, benderl commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +		</openwb-base-select-input>
Elemente ohne Inhalt können direkt als solche gekennzeichnet werden.
```suggestion
		/>
```

2024-04-25 10:55 UTC, pama87 commented on src/components/electricity_tariffs/energycharts/electricity_tariff.vue
> +		</openwb-base-select-input>
Done

2024-04-25 10:57 UTC, benderl approved these changes

2024-06-12 09:54 UTC, merged