add B23 to openWBflex->EVUKit flex and openWBEVUKit
openWB/openwb-ui-settings pull request #453
Opened 2024-04-22 13:25 UTC by pama87

2024-04-25 09:12 UTC, benderl requested changes
Bitte prüf doch auch noch in den anderen VUE-Dateien der `openwb_*` Module, ob die Auswahlliste sortiert ist. Kann dann gerne in diesen PR mit rein.

2024-04-25 09:12 UTC, benderl commented on src/components/devices/openwb_evu_kit/counter.vue
> +				{ value: 3, text: 'B23' },
```suggestion
				{ value: 3, text: 'B23' },
				{ value: 1, text: 'Lovato' },
				{ value: 0, text: 'MPM3PM' },
				{ value: 2, text: 'SDM630/SDM72D-M' },
```
Ich bin immer ein Freund davon, Auswahllisten alphabetisch zu sortieren. Dem Anwender sind die dahinter liegenden Werte ja ziemlich egal.

2024-04-25 09:12 UTC, benderl commented on src/components/devices/openwb_flex/counter.vue
> +				{ value: 3, text: 'B23' },
```suggestion
				{ value: 3, text: 'B23' },
				{ value: 1, text: 'Lovato' },
				{ value: 0, text: 'MPM3PM' },
				{ value: 2, text: 'SDM630/SDM72D-M' },
```

2024-04-25 09:20 UTC, pama87 commented on src/components/devices/openwb_flex/counter.vue
> +				{ value: 3, text: 'B23' },
done

2024-04-26 05:56 UTC, benderl approved these changes

2024-06-12 09:53 UTC, merged