setting limit bat power
openWB/openwb-ui-settings pull request #545
Opened 2024-09-03 07:43 UTC by LKuemmel

2024-09-13 07:31 UTC, benderl requested changes

2024-09-13 07:31 UTC, benderl commented on src/components/devices/mqtt/bat.vue
> +					><br />
```suggestion
					>
						openWB/bat/{{
							componentId
						}}/set/power_limit
					</openwb-base-copy-to-clipboard>
					<br />
```

2024-09-13 07:31 UTC, benderl commented on src/components/devices/mqtt/bat.vue
> +					werden muss<br />
```suggestion
					werden muss.<br />
```

2024-09-13 07:31 UTC, benderl commented on src/views/GeneralChargeConfig.vue
> +							zur Speicher-Beachtung im Modus PV-Laden.
```suggestion
							Wenn das Entladen des Speichers immer erlaubt ist,
							wird das Fahrzeug aus dem Speicher geladen anstatt
							Strom aus dem Netz zu beziehen. <br />
							Im Modus "gesperrt, wenn Fahrzeug lädt", wird die
							Entladung nur zugelassen, wenn alle Fahrzeuge im
							Modus PV-Laden ohne Mindeststrom oder Zielladen mit
							PV-Überschuss laden.<br />
							Wenn das Entladen des Speichers auf den
							Hausverbrauch begrenzt ist und mindestens Fahrzeuge
							nicht im Modus PV-Laden ohne Mindeststrom oder
							Zielladen lädt, wird die Entladung des Speichers in
							Höhe des Hausverbrauchs zugelassen. Kann die
							Entladung am Speicher nur komplett gesperrt werden,
							verhält sich diese Einstellung wie "gesperrt, wenn
							Fahrzeug lädt".<br />
							Diese Einstellung übersteuert ggf die Einstellungen
							zur Speicher-Beachtung im Modus PV-Laden.
```

2024-09-13 07:31 UTC, benderl commented on src/views/GeneralChargeConfig.vue
> +				"openWB/bat/set/power_limit_controlable",
Müsste das Topic nicht `../get/...` heißen? Das ist ja eine Eigenschaft, die das Speicher-Modul liefert. Keine Option, welche im Speicher gesetzt werden kann.
```suggestion
				"openWB/bat/get/power_limit_controlable",
```

2024-09-25 10:44 UTC, LKuemmel commented on src/views/GeneralChargeConfig.vue
> +				"openWB/bat/set/power_limit_controlable",
Stimmt, ist angepasst.

2024-09-26 06:17 UTC, benderl approved these changes

2024-10-08 10:32 UTC, benderl approved these changes

2024-10-10 12:21 UTC, merged