Systembericht-Angaben  Issue:#101.   Systembericht mit zusätzlichen Daten vorbelegen #101
openWB/openwb-ui-settings pull request #546
Opened 2024-09-03 12:57 UTC by Brett-S-OWB

Systembericht-Angaben automatisch vorbelegt,

Es könnte sein dass irgendwann die maximale Eingabe von 500 Zeichen überschreiten würde, falls viele Komponenten eingerichtet sind. Frage wäre dann ob besonders bei installierte Komponenten ob dies erhöht werden solle oder die Text-Beschreibung verschlankt werden soll.

2024-09-09 15:38 UTC, Brett-S-OWB commented
New commit: Remove unnecessary text from output...   (Um Ausgabetext-Größe zu reduzieren )

2024-09-10 08:25 UTC, benderl requested changes
Zusätzlich zu den Anmerkungen im Code bitte die Änderungen an `package-lock.json` aus diesem PR entfernen. Aktualisierte Pakete sollten immer in einem getrennten PR eingestellt werden, da es potentiell eher zu Problemen mit der Kompatibilität kommen kann.

2024-09-10 08:25 UTC, benderl commented on src/views/Support.vue
> +			for (const [, deviceConfig] of Object.entries(devices)) {
`Object.entries()` gibt `key`-`value` Paare zurück. Wenn der `key` hier nicht benötigt wird, sollte besser `Object.values()` verwendet werden.
```suggestion
			for (const deviceConfig of Object.values(devices)) {
```

2024-09-10 08:25 UTC, benderl commented on src/views/Support.vue
> +			return serial[serialKey];
Es gibt nur ein Topic für die Seriennummer. `getWildcardTopics()` macht also keinen Sinn. Einfach direkt auf den Store mit dem Topic zugreifen.

2024-09-10 08:25 UTC, benderl commented on src/views/Support.vue
> +				);
Auch hier gibt es nur ein Topic. Bitte direkt auf den Store zugreifen.
Damit es einfacher lesbar ist, sollte die lokale Variable nicht `vehicleDetails` sondern `vehicleInfo` heißen. Dann ist der Bezug zur Datenherkunft.

2024-09-10 08:25 UTC, benderl commented on src/views/Support.vue
> +				vehicleText += `ID: ${vehicleId} Name:${vehicleName}\n`;
Die Formatierung mit Zeilenumbruch und später in Z. 286 Einrückung sieht im Textfeld nett aus, geht aber im Systembericht leider verloren. Daher besser pro Fahrzeug alle Daten in einer Zeile erstellen.

Um es übersichtlicher zu machen, kann die komplette Zeile zu einem Fahrzeug in einer Operation zusammengefasst werden. Also die Zeilen 274 und 286 entfernen und in Zeile 288 den kompletten Text erzeugen.
```javascript
vehicleText += `ID: ${vehicleId} Name: ${vehicleName} Man.: ${make} Mod.: ${model}\n`
```

2024-09-10 08:25 UTC, benderl commented on src/views/Support.vue
> +	watch: {
Sind diese Watcher zwingend notwendig? Dann wird irgendwo im Code die normale "reactivity" von Vue gebrochen und sollte dort korrigiert werden. Ein Watcher ist nur in ganz seltenen Fällen erforderlich.

2024-09-13 07:32 UTC, benderl commented
Du müsstest noch `package-lock.json` aus dem PR entfernen.

2024-09-13 08:43 UTC, Brett-S-OWB commented
package-lock.json und package.json zu upstream (main) repo angepasst.

2024-09-13 08:54 UTC, benderl approved these changes

2024-09-16 06:38 UTC, merged