Add downloadUrlYear() to Download Charge Log for Year.
openWB/openwb-ui-settings pull request #584
Opened 2024-11-17 20:21 UTC by Sleepwalker86

2024-11-19 06:50 UTC, benderl requested changes

2024-11-19 06:50 UTC, benderl commented on public/downloadChargeLog.php
> +// Wenn der Monat angegeben ist und gültig, dann verwenden wir diesen Monat
Please use English vor comments in the code.

2024-11-19 06:50 UTC, benderl commented on public/downloadChargeLog.php
> +if (isset($_GET["month"]) && preg_match("/^((0?[1-9])|(1[0-2]))$/", $_GET["month"])) {
This modification lacks the check for invalid data on `$_GET["month"]`. If "month" is set and the regex does not match, there should be an `http error 400`.

2024-11-19 06:50 UTC, benderl commented on src/views/ChargeLog.vue
> +      const baseUrl = `${location.protocol}//${location.hostname}:${port}/openWB/web/settings/downloadChargeLog.php`;
As we have two URLs now, the property `downoadURL()` should be renamed to something more meaningful like `downloadUrlMonth()`.

Please do not duplicate code. Create a new computed property for the `baseURL` and make use of it in `downloadUrlMonth()` and `downloadUrlYear()`.

2024-11-21 12:13 UTC, benderl approved these changes

2024-12-05 08:30 UTC, benderl commented on src/views/ChargeLog.vue
> +      const baseUrl = `${location.protocol}//${location.hostname}:${port}/openWB/web/settings/downloadChargeLog.php`;
@Sleepwalker86 just a reminder

2024-12-09 07:51 UTC, Sleepwalker86 commented
i hope now is all fine

2024-12-12 15:39 UTC, benderl commented on src/views/ChargeLog.vue
> +    }
```suggestion
    },
```

2024-12-17 10:30 UTC, merged