Add Bootstrap-Vue-Next for enhanced table support and UI updates
openWB/openwb-ui-settings pull request #592
Opened 2024-11-29 17:37 UTC by MartinRinas

Integrate Bootstrap-Vue-Next for improved table functionality and update styles for the InverterCard and alert components to enhance visual consistency and user experience.

2024-11-29 17:41 UTC, MartinRinas commented
@benderl  ich hab' heute mit Hilfe von ChatGPT und GitHub Copilot mit an einem Update für die Inverter Karte auf der Statusseite beschäftig. Was haltet ihr davon, könntet ihr euch damit anfreunden? Den Code muss ich sicher noch ein wenig aufräumen, z.b. versuchen eine der Tabellenstruktur bzw. Definition als importierbare Komponente analog zu OpenWBBase*.vue. Und natürlich vergleichbare Anpassungen an den anderen Statuskarten. 

Bevor ich hier weiter mache wollt' ich aber mal hören was ihr davon haltet.

2024-11-29 21:11 UTC, MartinRinas commented
nach den letzten Updates sieht das nun so aus. Bei Warnung oder Fehler wird ein Statusindikator im Header angezeigt. Statusmeldung ist nun in den Footer gewandert.
![image](https://github.com/user-attachments/assets/0082fe4a-10da-440c-a5cd-1a71121d2b17)

2024-12-02 07:20 UTC, MartinRinas commented
so sieht das nun aus. Tabellen werden auch mit den großen Zahlen gut dargestellt, sowohl Desktop, mobile, breiter und schmaler Ansicht. Falls eine Warnung oder ein Fehler vorliegt wird die aktuelle Leistung durch ein entsprechendes Label (button) ersetzt. 
![image](https://github.com/user-attachments/assets/5c633920-c23b-4b71-a9b5-d05815ec37da)

2024-12-02 12:10 UTC, benderl requested changes
Danke für Deine Anpassungen.
Rein optisch sieht die überarbeitete Karte definitiv hübscher aus. Wenn Du magst, kannst Du das gerne auch für die anderen Karten weiter umsetzen.
Ein paar Anmerkungen habe ich inline gemacht.

2024-12-02 12:10 UTC, benderl commented on src/components/OpenwbBaseAlert.vue
> +<style scoped lang="scss">
```suggestion
<style scoped>
```

2024-12-02 12:10 UTC, benderl commented on package.json
> +    "sass": "^1.81.0",
Ich glaube nicht, dass das Modul benötigt wird. Deine Erweiterungen in den `<style>` Tags verwenden keine SASS spezifische Syntax. Dadurch sollten auch alle Änderungen an der Datei `package-lock.json` hinfällig werden.
```suggestion
```

2024-12-02 12:10 UTC, benderl commented on src/components/status/InverterCard.vue
> +      statusLevel: ["success", "warning", "danger", "primary", "secondary", "light", "dark"],
Der `statusLevel` ist im Backend definiert und kann nur 0, 1 oder 2 sein. Bitte diese Variable nicht dazu verwenden, weitere Formatierungsklassen zu definieren.

2024-12-03 09:28 UTC, MartinRinas commented
@benderl ich hab' mal die weiteren Karten welche ich direkt testen kann alle aktualisiert. Offen sind noch die BatSumCard (sollte einfach sein) sowie die beiden für variable Stromtarife und RSE. Das muss ich mir mal anschauen, ich hab' diese Komponenten nicht, ggf. bekomm' ich das in den Simulator integriert.

2024-12-05 08:27 UTC, benderl requested changes
Ein paar kleine Anmerkungen findest Du inline.
Zusätzlich bitte die Datei `package-lock.json` wieder zurücksetzen. Am Besten einfach aus dem main Branch in diesen kopieren.

Danach kann ich einen Feature-Branch erstellen und ein komplettes Review machen.

2024-12-05 08:27 UTC, benderl commented on src/components/status/ChargePointCard.vue
> +            <td class="text-right">🔌Strom</td>
Bitte für Symbole durchgängig FontAwesome verwenden.
Ich frage mich auch, warum ausgerechnet beim Strom eines angezeigt werden soll. Entweder einheitlich mit oder ohne Symbol. Alle Werte mit Symbolen zu versehen wäre vermutlich zu überfrachtet und bunt.

2024-12-05 08:27 UTC, benderl commented on src/components/status/CounterCard.vue
> +            <td class="text-right">🔌Strom</td>
Bitte das Symbol entfernen. Siehe auch weiter ohen.

2024-12-06 08:27 UTC, benderl approved these changes

2024-12-06 08:30 UTC, merged