JSON SoC
openWB/openwb-ui-settings pull request #598
Opened 2024-12-13 10:19 UTC by MartinRinas

2024-12-17 10:34 UTC, benderl requested changes
Nur ein Copy/Paste Fehler.

2024-12-17 10:34 UTC, benderl commented on src/components/vehicles/json/vehicle.vue
> +  name: "VehicleSocHttp",
```suggestion
  name: "VehicleSocJson",
```

2024-12-17 13:19 UTC, benderl approved these changes

2024-12-19 07:16 UTC, LKuemmel approved these changes

2024-12-19 09:24 UTC, merged